### ISSUE TITLE
Feature Request: Add documentation regarding the 3.x > 4.x migration

### ISSUE THREAD

**Issue by BrodaNoel** [fnando/i18n#107]
## Description
I'm using `i18n-js` 3.x, and I want to migrate to 4.x, but I can't find any documentation about which are the breaking changes.

## Describe the solution
The description of the breaking changes, in the CHANGELOG file

## Alternatives you considered
n/a

## Additional context
n/a

**Comment by fnando** [comment]
Here it is! https://github.com/fnando/i18n-js/blob/main/MIGRATING_FROM_V3_TO_V4.md
