### ISSUE TITLE
Feature Request: To allow passing `missingBehavior` as option to `translate`

### ISSUE THREAD

**Issue by eugenet8k** [fnando/i18n#12]
## Description

At this point, the `missingBehavior` is one of the i18n options that is set at the class instance creation https://github.com/fnando/i18n/blob/60bb7f810c59e9a40ad349021855a8175210dbb0/src/I18n.ts#L216

Having a few strategies of how to deal with a missing translation is great, but a lot of times we UI would benefit from a dynamic choice of what behavior to use for a particular UI place.

For example, if I have a enumerable set of translations for some predefined types: "cat", "dog", "rat".

```yaml
en:
  animals:
    cat: Cat
    dog: Dog
    rat: Rat
```

and I have a UI

```js
const getAnimalLabel = (type) =>
  <span class="my-animal">{i18n.t(`animals.{type}`)}</span>
```

I want this function to return an empty `span` if there is no translation. I don't want an error or a string like `<span>"[missing "animals.bird" translation]"</span>` for this particular UI place. Currently, there is no easy way to deal with this simple case.

## Describe the solution

There is a small solution that unlocks this scenario, just updating a single line https://github.com/fnando/i18n/blob/60bb7f810c59e9a40ad349021855a8175210dbb0/src/MissingTranslation.ts#L152

into
```js
  public get(scope: Scope, options: Dict): string {
    return this.registry[options.missingBehavior || this.i18n.missingBehavior](this.i18n, scope, options);
  }
```

in this case, I could register my custom strategy:

```js
const emptyStrategy = () => undefined

class PatchedMissingTranslation extends MissingTranslation {
  constructor(...args) {
    super(...args)
    this.register('empty', emptyStrategy)
  }
}
```

And use it in my code:

```js
const getAnimalLabel = (type) =>
  <span class="my-animal">{i18n.t(`animals.{type}`, {missingBehavior: 'empty'})}</span>
```

## Alternatives you considered

The alternative is to override the `get` method in the user code. This works but maybe a problem in the long run if the i18n would change the `MissingTranslation` implementation

## Additional context

Also, it would be great to include a suggested `empty` strategy into the list of default strategies https://github.com/fnando/i18n/blob/60bb7f810c59e9a40ad349021855a8175210dbb0/src/MissingTranslation.ts#L109-L111

**Comment by fnando** [comment]
I like this. I implemented it on 8a403e00d3c9babc7f34dd2d647da9dd4da83b96.
