### ISSUE TITLE
Why dependencies on bignumber.js and lodash

### ISSUE THREAD

**Issue by shivam091** [fnando/i18n#19]
Hi,

I simply want to perform translations without use of above two libraries. When I add this library using importmap on Rails 7 application, it also adds bignumber and lodash in my assets.

I still get error even when I added these two files in my assets.
I get error as  "The requested module 'lodash' does not provide an export named 'flattenDeep'".

Is there any specific reason that these two libraries are automatically added when we add i18n library?

Can you help me out how I can get it fixed?

Thanks.

**Comment by fnando** [comment]
Hey!

bignumber.js is used for all number related helpers, like `I18n#numberToHuman`. It's an important dependency and can't be removed. 

As for lodash, we use it to avoid redoing work that's already been done. Can you please tell me which lodash version you have on your project?

**Comment by shivam091** [comment]
I agree what you said about requirement of two lib. in your library.

I first tried with 4.17.21 and later with 4.17.15.
Both these JS files has method `flattenDeep` which my application is saying that export named flattenDeep not present in 'lodash'.


My importmap entries for this

pin "i18n-js", to: "https://ga.jspm.io/npm:i18n-js@4.0.0-alpha.14/dist/import/index.js"
pin "bignumber.js", to: "https://ga.jspm.io/npm:bignumber.js@9.0.2/bignumber.js"
pin "lodash", to: "https://ga.jspm.io/npm:lodash@4.17.21/lodash.js"

**Comment by shivam091** [comment]
Let me know whether we can handle this error in this lib. or I must raise it to lodash community.

Thanks.

**Comment by fnando** [comment]
Can you please please upload a sample app reproducing the issue? It'll be easier to debug.

**Comment by shivam091** [comment]
> Can you please upload a sample app reproducing the issue? It'll be easier to debug.

Okay.

**Comment by bmesuere** [comment]
For our project, these new dependencies are also an unwelcome side effect of the new release. They add quite a bit to our bundle size (which contradicts the "small" in the project description).

We'll probably pin the old version to work around this issue.

**Comment by xkraty** [comment]
I've found out the default version is not modularized, there is a [lodash es package ](https://www.npmjs.com/package/lodash-es).
