### ISSUE TITLE
Bug: i18n.t return type shouldn't be only string

### ISSUE THREAD

**Issue by mgruntowski** [fnando/i18n#29]
## Description

i18n allows us to return a translation for a scope as an array or an object, but `i18n.t` has only `string` as return type, causing TypeErrors if you try to use it as something that isn't a string.

## How to reproduce

Just try to use a directly return from i18n.t as `string[]` or some object type.

## What do you expect

`i18n.t` should have more than just string as return type.

## What happened instead

TypeError, because `i18n.t` always return a string, according to its type.

**Comment by fnando** [comment]
Usually, I just do a `as unknown as string[]`, but maybe this should be injectable, like `i18n.t<string[]>(…args)`. Suggestions?

**Comment by fnando** [comment]
Another thing to keep in mind is that the function return's type would likely have to be `T | string`, because there's the missing translation type, which is a string.

**Comment by mgruntowski** [comment]
> Usually, I just do a as unknown as string[], but maybe this should be injectable, like i18n.t<string[]>(…args). Suggestions?

I'm also using the `as unknown as string[]` workaround, but I prefer the injectable solution. I agree with the type being `T | string` too.
