### ISSUE TITLE
Bug: `toNumber` method disappeared in v4

### ISSUE THREAD

**Issue by mmmoussa** [fnando/i18n#32]
## Description

In v3 of this library there was a `.toNumber` method that appears to have been replaced by a `formatNumber` helper in v4, however, that helper is not exported. Is there a reason for not exporting it? Additionally, the old method [is still being mentioned in one place in the README](https://github.com/fnando/i18n#using-pluralization-and-number-formatting-together) which is wrong.

## How to reproduce

`i18n.toNumber()`

## What do you expect

`i18n.toNumber()` does not throw an error, or is replaced by `i18n.formatNumber` which is publicly accessible and uses the `formatNumber` helper

## What happened instead

`i18n.toNumber()` throws an error

## Software:

- Gem version: N/A
- Ruby version: N/A

## Full backtrace

```text
TypeError: undefined is not a function
```

**Comment by fnando** [comment]
Closed by https://github.com/fnando/i18n/commit/4fa4d66feab5e01f06a969e7ddc136d259efdd72
