### ISSUE TITLE
Bug: Error importing flattenDeep module from Lodash using importmap

### ISSUE THREAD

**Issue by dukebrown** [fnando/i18n#42]
When using the library with importmap the following error is thrown:
```
The requested module 'lodash' does not provide an export named 'flattenDeep'
```

The offending code appears to be at the very top of /dist/import/index.js, in the first import statement:
```
import{uniq as e,camelCase as n,repeat as r,get as i,zipObject as s,sortBy as o,flattenDeep as a,isArray as l,isObject as c,range as u,set as h,has as d}from"lodash";
```

I'm able to reproduce the error in JSPM's [sandbox](https://jspm.org/sandbox#H4sIAAAAAAAAA31U30/bMBB+5684shfQmriphgYlqYCBEGxFaFk38egm18YssSPbIWSI/30Xpz8AbTy0lu/O39333V2i3Uyltq0QclsWk51ofSDPJjsAUYmWQ5pzbdDGXm0X/qHnHFbYAicz6c4sYv1980TyEmPvQWBTKW09SJW0KAmiEZnN4wwfRIq+uwxASGEFL3yT8gLjkBJErK8gmqusdai7vk8HwHVyO4VLlKi5VRquyg4fprxy3otMWJh9/zYmPrYyY8aW69Dg3lRlIBT7MBv9zO8uz36fT4e6Tf5cJ7Mwb8+TYXtze/NV3jXDH7fJtDk9Pajq0fysOSVk33dFmFSLykInWOwJl7rklRPkyeVfGY03Xhk6U3go/fvO5G2K4ptqZFWOVxEnn4JRMGSZMJb1OEzIDB8p1nNgz4M+iUlVha9y/AP4hZsC5mIp63KOnQzvVPIy7OQoCIOQbU0lPR1sIQuVcZO/A9YHEKvwczAKWX/dkCE6O+v/7hexXt1OzFXD4SKBqcrqAiHJRWnG63aT6AYqVbQLURSwoDkoXZiBuVaNQW2gETZXtQXx4oWpK3fZ4/QKH1OkXn7JtSoRDo8+7r/pMjetTMHoNP4fQTR+n9c3XXknYXBAgrn+vXF1rCHVyhilxVLI2ONSybZUtfEmb5m/mrIexY0YrMk8QTcx1waeYUHVb0fsuEcAYAx+aWGReAu5Eod2MKM9R40DIMW4AQ4GK07bgUBCotOMjB5x9oBbq8W8Jp+SYHNco/TVBS4NbbVRBQaFWu71Je0fv2plxPoFpn12H5a/GJ7sBnAEAAA=) using the following code:
```
<script type="importmap">
{
  "imports": {
    "i18n-js": "https://ga.jspm.io/npm:i18n-js@4.2.0/dist/import/index.js"
  },
  "scopes": {
    "https://ga.jspm.io/": {
      "bignumber.js": "https://ga.jspm.io/npm:bignumber.js@9.1.1/bignumber.mjs",
      "lodash": "https://ga.jspm.io/npm:lodash@4.17.21/lodash.js"
    }
  }
}
</script>
<script type="module">
  import { i18nJs } from "i18n-js";
  console.log(i18nJs);
</script>
```

I don't see anything wrong with the import statement, but then again exports/imports aren't really in my wheelhouse. Could the problem instead be with the way Lodash exports flattenDeep?

Thanks!

**Comment by fnando** [comment]
We're moving away from loading lodash (the global package) to require specific modules we need (see #41). I can make a release with it to see if it helps with anything. Wdyt?

**Comment by fnando** [comment]
Oh, another thing to try: use https://www.npmjs.com/package/lodash-es instead. https://github.com/fnando/i18n/issues/19#issuecomment-1324011937

**Comment by fnando** [comment]
I make it work with this, but there's a catch: it works if I save it as a HTML file, but not if I try to run from JSPM's sandbox.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Untitled</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <!--
    JSPM Generator Import Map
    Edit URL: https://generator.jspm.io/#U2VhYGBkDM0rySzJSU1hyDS0yNPNKnYw0TPSMwAA5pu2bBwA
  -->
    <script type="importmap">
      {
        "imports": {
          "i18n-js": "https://ga.jspm.io/npm:i18n-js@4.2.0/dist/import/index.js",
          "bignumber.js": "https://ga.jspm.io/npm:bignumber.js@9.1.1/bignumber.mjs",
          "lodash": "https://ga.jspm.io/npm:lodash-es@4.17.21/lodash.js"
        }
      }
    </script>

    <!-- ES Module Shims: Import maps polyfill for modules browsers without import maps support (all except Chrome 89+) -->
    <script
      async
      src="https://ga.jspm.io/npm:es-module-shims@1.5.1/dist/es-module-shims.js"
      crossorigin="anonymous"
    ></script>

    <script type="module">
      import { I18n } from "i18n-js";

      const i18n = new I18n({
        en: { hello: "Hello!" },
        pt: { hello: "Olá!" },
      });

      console.log("en.hello:", i18n.t("hello"));

      i18n.locale = "pt";

      console.log("pt.hello:", i18n.t("hello"));
    </script>
  </body>
</html>
```

**Comment by dukebrown** [comment]
Thanks for the incredibly quick response, @fnando! And thanks for the suggestion. The problem does indeed appear to be with the Lodash package at JSPM.

I was able to get it to work with the Lodash ES package at https://cdn.jsdelivr.net/npm/lodash-es@4.17.21/lodash.js instead.

(It also works in the JSPM sandbox, but only if you change the module's import statement to:
```
import * as i18nJs from "i18n-js";
```

Thanks again!
