### ISSUE TITLE
Official way to use require folder instead of import

### ISSUE THREAD

**Issue by LaGregance** [fnando/i18n#53]
I'm currently looking for a way to use this package using React & Next.js but I get the following error `Unexpected token 'export'` due to the fact I can only use commonjs package.

Regarding the structure of the project I can see 3 folders under the dist folder : import, browser & require. The main file registered in package.json is `dist/import/index.js`.

So I found 2 way to fix this:
 - Import `i18n-js/dist/require` but in Typescript I get the following error `Could not find a declaration file for module i18n-js`
 - Create a fork of the project that only change the main file to `dist/require/index.js`

So I go into the second solution, for those facing the same issues you can find the package here: https://www.npmjs.com/package/@lagregance/i18n-js-require

Maybe I miss it, but since the relevant package is available inside the dist folder we should have a way to use it without making a fork (my idea is to publish alternative version like `4.2.2_require`).

Thanks for help.

**Comment by iamwill123** [comment]
running into the same issue

**Comment by VictorDeel** [comment]
Same, really need it supported officially :)

**Comment by fnando** [comment]
My take on this is that @Crisfole seems like a good approach, but you can avoid the `@ts-ignore` by creating a `module.d.ts` file with something like `declare module 'i18n-js/dist/require'`.
