### ISSUE TITLE
Error: While trying to resolve module `make-plural`

### ISSUE THREAD

**Issue by lucianolopezz** [fnando/i18n#64]
## Description

I have a React Native project that using i18n-js. But when I execute the building, I have the following error:

`Error: While trying to resolve module `make-plural` from file `/node_modules/i18n-js/dist/import/Pluralization.js`, the package `/node_modules/make-plural/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/node_modules/make-plural/plurals.mjs`. Indeed, none of these files exist:`

"React native": "0.67.5"
"i18n-js": "^4.2.3"

**Comment by fnando** [comment]
Please take a look at the readme:

https://github.com/fnando/i18n#im-getting-an-error-like-unable-to-resolve-make-plural-from-node-modulesi18n-jsdistimportpluralizationjs

**Comment by brada1703** [comment]
For anyone else who sees this:

Create a "metro.config.js" file in the root directory of your project with the following code:

const { getDefaultConfig } = require("metro-config");

```
module.exports = (async () => {
  const {
    resolver: { assetExts, sourceExts },
  } = await getDefaultConfig();

  return {
    resolver: {
      sourceExts: [...sourceExts, "mjs"],
    },
  };
})();
```
