### ISSUE TITLE
Feature Request: reconsider vendoring lodash

### ISSUE THREAD

**Issue by tagliala** [fnando/i18n#65]
## Description

Hi, the newly released v4.3.0 vendored the whole lodash library to improve compatibility with importmap

However, this choice comes with some drawbacks, like:
- File size increased by more than 500%, from [1.4MB](https://www.npmjs.com/package/i18n-js/v/4.2.3) to [7.53MB](https://www.npmjs.com/package/i18n-js/v/4.3.0)
- Inability to reuse code from lodash, if other libraries are using the same lodash functionalities
- Update concerns: the gem will require a release after each lodash release
- Security concerns: if a new CVE will be found in lodash affecting one of the functionalities used in i18n-js, this library will potentially be exposed to CVEs
- Issues with third-parties:  #66

## Describe the solution

I do not know a solution, I'm going to make some proposals:
- Vendor just the minimum amount of code possible
- Remove unnecessary lodash dependencies, like the deprecated `isArray` (probably a breaking change that require a major release)
- Check if this is an issue with importmap not being able to resolve lodash, or with lodash itself. This is probably related to https://github.com/lodash/lodash/issues/4366#issuecomment-511485328

## Alternatives you considered

- Fork
- Lock to 4.2.3

## Additional context

I'm not a JavaScript developer, but I'm willing to help in finding an alternative

**Comment by fnando** [comment]
Hello @tagliala. Which bundler (webpack, esbuild, other) are you using? If I bundle the file below, I get 66kb on the latest version using webpack (`webpack bundle --mode production --entry ./index.mjs --output-filename webpack.js`):

```
import { I18n } from "i18n-js";

const i18n = new I18n({
  en: { hello: "Hello" },
  pt: { hello: "Olá" },
  es: { hello: "Hola" },
});

const sayHello = () => console.log(i18n.t("hello"));

i18n.withLocale("en", sayHello);
i18n.withLocale("pt", sayHello);
i18n.withLocale("es", sayHello);
```

**Comment by tagliala** [comment]
Hi,

> If you're concerned about the actual package size, I'd like to hear more about it.

Correct, my main concern is about package size

As a reference, this is the actual space on the disk

```sh
# 4.2.3
$ du -h node_modules/i18n-js/
2.2M	node_modules/i18n-js/

# 4.3.0
$ du -h node_modules/i18n-js/
 33M	node_modules/i18n-js/
```

As per the build size, I'm not a JavaScript developer and I struggle into providing test cases and testing what I think, but you may check if something like

```js
import { I18n } from "i18n-js"
import { get } from "lodash"
import { has } from "lodash"
import { set } from "lodash"
import { uniq } from "lodash"

console.log(I18n)
console.log(get)
console.log(has)
console.log(set)
console.log(uniq)
```

Can potentially provide two implementations of `get` and `has` in the output file

**Comment by fnando** [comment]
honestly, i don't think package size seems that big of deal. I prefer making things easier for users that want to do importmaps. In any case, we're bundling less stuff right now, and the installation size with all dependencies is `8.1M` as of the latest release (v4.3.2).
