### ISSUE TITLE
Feature Request: About Vendor Lodash

### ISSUE THREAD

**Issue by pinchtools** [fnando/i18n#66]
## Description

I had a problem with the 4.3.0 that I wanted to share.
My Nuxt 3 production build failed because of relative dependencies added  in the generated js.
It took me a while to realize it came from the i18n package.
The relatives path added in the nuxt generated js concerned your '/src/vendor/lodash' directory

## Describe the solution

Anyway, browsing in your repo I see that these directory has been remove in 4.3.1-beta. So I upgrade and it's ok now.

**Comment by tagliala** [comment]
I think that this can be considered a "duplicate" of #65

**Comment by fnando** [comment]
v4.3.1, which undoes lodash's vendoring.
