### ISSUE TITLE
i18n.numberToPercentage(undefined) throws an error

### ISSUE THREAD

**Issue by eugenet8k** [fnando/i18n#8]
## Description

```
i18n.numberToPercentage(undefined)
```

Throws an error:

```
TypeError: Cannot read properties of undefined (reading 'toString') (webpack-internal:///./node_modules/i18n-js/dist/import/helpers/formatNumber.js:60)
```

The original code is here https://github.com/fnando/i18n/blob/main/src/helpers/formatNumber.ts#L89

```
  if (originalNumber.isNaN()) {
    formattedNumber = input.toString();
  }
```

## What do you expect

The function will return undefined if the `input` is undefined

## Software:

```
"i18n-js": "4.0.0-alpha.14"
```

**Comment by fnando** [comment]
Hi @eugenet8k. The expected `input` type is `Numeric`, which expands to `BigNumber | string | number`. The client needs to ensure that's sending one of those types.

**Comment by fnando** [comment]
That's also the case for `numberToDelimited`; the `input` type is `Numeric`.

**Comment by eugenet8k** [comment]
If it is expected behavior, it would be great to throw an error that points this out. Something like `throw new TypeError('The input should only by of type Numeric')`

But generally, I18n v3:

```
I18n.toPercentage(55, {precision: 0})
'55%'
I18n.toPercentage(null, {precision: 0})
'0%'
I18n.toPercentage(undefined, {precision: 0})
'NaN%'
```

```
I18n.toNumber(55555, {precision: 0})
'55,555'
I18n.toNumber(null, {precision: 0})
'0'
I18n.toNumber(undefined, {precision: 0})
'NaN'
```

I18n v4:
```
I18n.numberToPercentage(55, {precision: 0})
'55%'

I18n.numberToPercentage(null, {precision: 0})
formatNumber.js:60 Uncaught TypeError: Cannot read properties of null (reading 'toString')
    at formatNumber (formatNumber.js:60:33)

I18n.numberToPercentage(undefined, {precision: 0})
formatNumber.js:60 Uncaught TypeError: Cannot read properties of undefined (reading 'toString')
    at formatNumber (formatNumber.js:60:33)
```

We are just migrating to v4. I think it would be great to preserve the API behavior, as having checks between each call just makes the code looks polluted.

If anyone struggles with the issue, a workaround patch would be something like:

```
const {I18n} = require('i18n-js')

const castNumberInput = input =>
  input === null ? 0 : input === undefined ? Number.NaN : input

// TODO: Remove the Patch if https://github.com/fnando/i18n/issues/8 was resolved favorably
class PatchedI18n extends I18n {
  numberToCurrency(input, options) {
    return super.numberToCurrency(castNumberInput(input), options)
  }

  numberToPercentage(input, options) {
    return super.numberToPercentage(castNumberInput(input), options)
  }

  numberToRounded(input, options) {
    return super.numberToRounded(castNumberInput(input), options)
  }

  numberToDelimited(input, options) {
    return super.numberToDelimited(castNumberInput(input), options)
  }
}
```

**Comment by fnando** [comment]
Sorry for now answering sooner.

Unfortunately, v4 is not 100% backwards compatible. I think your workaround is the way the go, if you can't guarantee the type you're passing to i18n.
