### ISSUE TITLE
Bug: Documentation doesn't match implementation or types

### ISSUE THREAD

**Issue by k4rli** [fnando/i18n#80]
## Description

[[https://github.com/fnando/i18n/tree/main#missing-translations]](https://github.com/fnando/i18n/tree/main#missing-translations) lists several ways to register fallback languages but that doesn't work.

```tsx
// Using an array
i18n.locales.register("no", ["nb", "en"]);

// Using a string
i18n.locales.no.register("nb");

// Using a function.
i18n.locales.no.register((locale) => ["nb"]);
```

Only the first variant works, i18n.locales.${localename}.register doesn't work.

Also when I tried to use the first variant `i18n.locales.register("de", ["en"]);` to set "en" as fallback for "de", then it failed with `i18n.t("existingkey")` even though `i18n.translations.de.existingkey` existed and `i18n.locale` was set to `de`.

## How to reproduce

`I18n.locales.de.register("en");`

## What do you expect

Missing behavior to be registered

## What happened instead

`- error TypeError: Cannot read properties of undefined (reading 'register')`

## Software:

- i18n-js version: 4.3.2

**Comment by fnando** [comment]
that's the old syntax, and it's no longer valid. I removed the reference from the readme.
