### ISSUE TITLE
numberToPercentage behaves inconsistent to arguments

### ISSUE THREAD

**Issue by eugenet8k** [fnando/i18n#9]
## Description

If `precision` option is not passed to `numberToPercentage` it will return  `'NaN%'` regardless of input

## How to reproduce

```
> I18n.numberToPercentage(55.55)

'NaN%'

> I18n.numberToPercentage(55.55, {precision: 0})

'56%'

```

## What do you expect

I'd expect a default precision to kick in and return a numeric string value. The same applies to `localize` calls, now it is

```
> I18n.l("percentage", 123.45)

'NaN%'
```

## Software:

"i18n-js": "4.0.0-alpha.14",

**Comment by fnando** [comment]
Thanks for reporting this issue. The problem was calling `I18n#numberToPercentage` without having loaded any base translations.

```
> i18n = new I18n()
> i18n.numberToPercentage(100)
'NaN%'
> i18n.store(require("./json/en.json"))
undefined
> i18n.numberToPercentage(100)
'100.000%'
```

This has been fixed on https://github.com/fnando/i18n/commit/60bb7f810c59e9a40ad349021855a8175210dbb0.
