### ISSUE TITLE
Bug: I18n is not a constructor

### ISSUE THREAD

**Issue by dpudev-zf** [fnando/i18n#95]
## Description
After updating the package all versions after 4.4.0. I'm getting error when I tryied to load the package with configurations.

## What do you expect
To run without errors.

## What happened instead

It getting error.

## Software:
i18n version > 4.4.0

## Full backtrace

<img width="667" alt="2024-02-14_16h16_22" src="https://github.com/fnando/i18n/assets/113181832/931f3741-310b-4b7a-9f04-c722c582fe7d">

**Comment by fnando** [comment]
Can you please test v4.4.3-beta.0? I'm undoing the change that broke exports.

**Comment by DennisHesler** [comment]
I didn't have that problem with this version "i18n-js": "^4.3.2", but today I started having that problem in that version, I tried to update and download the version but I still have the problem.
<img width="592" alt="image" src="https://github.com/fnando/i18n/assets/117657977/99fe5ca4-53d5-4f20-93e2-f5c36e5ef578">

<img width="592" alt="image" src="https://github.com/fnando/i18n/assets/117657977/8d0ab740-28d0-40c9-8eaa-36843c4fc4fd">

**Comment by fnando** [comment]
@DennisHesler That's because 4.4.0 introduced the change. Were you able to test 4.4.3-beta.0 out?

**Comment by DennisHesler** [comment]
I tried it there and in that version it is working. Will it be updated soon? At the moment I keep that i18n-js": "4.4.3-beta.0"
Thanks for response

**Comment by fnando** [comment]
Great! Yes, I'm planning to release 4.4.3 tonight (PDT) or tomorrow, depending on whether other people that contacted me confirm that it's working for them as well.

**Comment by raldred** [comment]
We across this in our update cycle, 4.4.3-beta.0 fixes issue for us. Thanks

**Comment by fnando** [comment]
just released 4.4.3.

**Comment by dpudev-zf** [comment]
I have tested and with the version 4.4.3 it is working, thanks
