### ISSUE TITLE
Chore: webpack (and probably esbuild) troubleshooting in the readme should not be needed anymore

### ISSUE THREAD

**Issue by tagliala** [fnando/i18n#96]
## Description

The instructions for using `webpack` with `i18n` at https://github.com/fnando/i18n?tab=readme-ov-file#im-using-webpack-and-bundling-doesnt-work are likely outdated and should be reviewed/removed.

These instructions were introduced due to issues with the `exports` field in version 4.4.1 of `i18n`. However, it seems these modifications caused further problems with `webpack` and `esbuild`. Additionally, changing the default `resolve.conditionNames` as advised might have unintended consequences for other libraries in large applications.

**Comment by fnando** [comment]
removed!
