### ISSUE TITLE
Feature Request: Support delimited numbers for pluralization

### ISSUE THREAD

**Issue by short-dsb** [fnando/i18n#98]
## Description

Numbers passed to `pluralize` via `count` are not delimited. For example, in `en-US`:

> 1234 results

…should be:

> 1,234 results

## Describe the solution

A possible solution is to pass an optional `displayCount` string that overrides the numeric `count` in the output. For example:

```ts
const resultsCount = 1234;

i18n.t("results", {
  count: resultsCount,
  displayCount: i18n.numberToDelimited(resultsCount),
});
```

This would give more control over how the output is formatted. For example, if someone wanted to use `numberToHuman` instead of `numberToDelimited`.

## Alternatives you considered

There’s no alternative to this as far as I can tell, given how `count` is parsed when a string is pluralized via `zero`, `one`, `few`, `many`, and `other`. Happy to be proven wrong. 🙂 

## Additional context

This is how pluralization works for [FBT](https://facebook.github.io/fbt/) via [`PluralOptions.value`](https://github.com/facebook/fbt/blob/main/packages/babel-plugin-fbt/src/FbtConstants.js#L59).

Thanks for all your work on this library!

**Comment by loiclouvet** [comment]
Does this solve your problem? @short-dsb 
https://github.com/fnando/i18n?tab=readme-ov-file#using-pluralization-and-number-formatting-together

**Comment by short-dsb** [comment]
It does, thank you. 🙂
